version: "2.3"

services:
  osrm-backend:
    # For production, download prebuilt image
    image: furyhawk/osrm-backend:${OSRM_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: osrm-backend
    ports:
      - "5000:5000"
    environment:
      # OSRM manager setup
      - OSRM_ALGORITHM=mld
      - OSRM_THREADS=2
      - OSRM_PORT=5000
      - OSRM_PROFILE=/opt/car.lua
      - OSRM_MAP_NAME=${OSRM_MAP_NAME}
      - OSRM_GEOFABRIK_PATH=${OSRM_GEOFABRIK_PATH}
      # Notify OSRM Manager to restart without stopping container
      - OSRM_NOTIFY_FILEPATH=/data/osrm_notify.txt

  # osrm_frontend:
  #   image: furyhawk/osrm-frontend:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   container_name: osrm-frontend
  #   # [TODO] Enable auto-restart when production-ready
  #   #restart: always
  #   # FIXME https://github.com/Project-OSRM/osrm-frontend/issues/278
  #   #command: npm run start-prod
  #   ports:
  #     - "5555:9966"
  #   depends_on:
  #     osrm-backend:
  #       condition: service_started
  #   environment:
  #     - OSRM_BACKEND=http://localhost:5000